[package]
name = "pigasio-core"
description = "Multi-device audio engine backing the PigASIO driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cpal = { workspace = true }
rubato = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
rtrb = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
audio_thread_priority = { workspace = true }
